# This file configures the $APP_NAME app which serves public web traffic on port 80
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      containers:
      - name: $APP_NAME
        image: ghcr.io/wulfland/release-recipe:sha-412aecc
        ports:
        - containerPort: 3000
            